# Generated by Django 4.1.3 on 2023-11-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookRec', '0002_feature_details_feature_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
