# Generated by Django 4.1.3 on 2023-11-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookRec', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
